apiVersion: v1
kind: PersistentVolume
metadata:
  name: smruti-pv
  namespace: demo
  labels:
    type: smruti-pv
spec:
  claimRef:
    name: smruti-pvc
    namespace: demo
  capacity:
    storage: 11Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/redis